name: Build Expo App

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: ğŸ›  Run version update script
        if: startsWith(github.ref, 'refs/tags/')
        run: node scripts/new-version.mjs ${{ github.ref_name }}

      - name: ğŸ”§ Configure Git
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ğŸ“¤ Commit version changes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout ${{ github.event.repository.default_branch }}
          git pull
          git add app.json package.json package-lock.json
          git commit -m "chore: update version to ${{ github.ref_name }}"
          git push origin ${{ github.event.repository.default_branch }}

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest
          packager: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ‘· Build expo app
        env:
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          eas build --local --non-interactive --output ./${{ github.ref_type == 'tag' && format('jellyseerr-{0}.apk', github.ref_name) || 'jellyseerr.apk' }} --platform android --profile preview

      - name: ğŸ“¦ Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_type == 'tag' && format('jellyseerr-{0}.apk', github.ref_name) || 'jellyseerr.apk' }}
          path: ./${{ github.ref_type == 'tag' && format('jellyseerr-{0}.apk', github.ref_name) || 'jellyseerr.apk' }}

      - name: ğŸš€ Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ github.ref_type == 'tag' && format('jellyseerr-{0}.apk', github.ref_name) || 'jellyseerr.apk' }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
