---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Expo App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android-phone:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest
          packager: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ‘· Build expo app
        env:
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          eas build --local --non-interactive --output ./${{ github.ref_type == 'tag' && format('seerr-{0}.apk', github.ref_name) || 'seerr.apk' }} --platform android --profile preview

      - name: ğŸ“¦ Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_type == 'tag' && format('seerr-{0}.apk', github.ref_name) || 'seerr.apk' }}
          path: ./${{ github.ref_type == 'tag' && format('seerr-{0}.apk', github.ref_name) || 'seerr.apk' }}

  build-ios-phone:
    runs-on: macos-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: ğŸ”§ Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest
          packager: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ‘· Build expo app
        env:
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          eas build --local --non-interactive --output ./${{ github.ref_type == 'tag' && format('seerr-{0}.ipa', github.ref_name) || 'seerr.ipa' }} --platform ios --profile preview

      - name: ğŸ“¦ Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_type == 'tag' && format('seerr-{0}.ipa', github.ref_name) || 'seerr.ipa' }}
          path: ./${{ github.ref_type == 'tag' && format('seerr-{0}.ipa', github.ref_name) || 'seerr.ipa' }}

  release:
    needs:
      - build-android-phone
      - build-ios-phone
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: ğŸ›  Run version update script
        run: node scripts/new-version.mjs ${{ github.ref_name }}

      - name: ğŸ”§ Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ğŸ“¤ Commit version changes
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout ${{ github.event.repository.default_branch }}
          git pull
          git add app.json package.json package-lock.json
          git commit -m "chore: update version to ${{ github.ref_name }}"
          git push origin ${{ github.event.repository.default_branch }}

      - name: ğŸ“¥ Fetch APK artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name && format('seerr-{0}.apk', github.ref_name) || 'seerr.apk' }}

      - name: ğŸ“¥ Fetch IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name && format('seerr-{0}.ipa', github.ref_name) || 'seerr.ipa' }}

      - name: ğŸ›  Generate a changelog
        id: changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff.toml
          args: -vv --current
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: ğŸš€ Create GitHub Release
        run: gh release create ${GITHUB_REF_NAME} -t "Release ${GITHUB_REF_NAME}" -n "${RELEASE_BODY}" ./seerr*.apk ./seerr*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BODY: ${{ steps.changelog.outputs.content }}